#!/bin/bash

set -e
human_readable() {
    local abbrevs=(
        $((1 << 60)):ZiB
        $((1 << 50)):EiB
        $((1 << 40)):TiB
        $((1 << 30)):GiB
        $((1 << 20)):MiB
        $((1 << 10)):KiB
        $((1)):bytes
    )

    local bytes="${1}"
    local precision="${2}"

    if [[ "${bytes}" == "1" ]]; then
        echo "1 byte"
    else
        for item in "${abbrevs[@]}"; do
            local factor="${item%:*}"
            local abbrev="${item#*:}"
            if [[ "${bytes}" -ge "${factor}" ]]; then
                local size="$(bc -l <<< "${bytes} / ${factor}")"
                LC_NUMERIC="en_US.UTF-8" printf "%.*f %s\n" "${precision}" "${size}" "${abbrev}"
                break
            fi
        done
    fi
}


RX=0
TX=0
INTERFACE=$(ip route get 1.1.1.1 | grep -Po '(?<=dev\s)\w+' | cut -f1 -d ' ')
RX=$(ip -s link show $INTERFACE | grep -A 1 RX | tail -n1 | awk '{print $1}')
TX=$(ip -s link show $INTERFACE | grep -A 1 TX | tail -n1 | awk '{print $1}')
sleep 1
RX=$(( $(ip -s link show $INTERFACE | grep -A 1 RX | tail -n1 | awk '{print $1}') - $RX ))
TX=$(( $(ip -s link show $INTERFACE | grep -A 1 TX | tail -n1 | awk '{print $1}') - $TX ))
DOWN=$(human_readable ${RX})
UP=$(human_readable ${TX})

echo "IN ${DOWN:-0} OUT ${UP:-0}" 
