#!/bin/sh

case $BLOCK_BUTTON in
	1) pavucontrol-qt ;; 
	2) pamixer -t ;;
	4) pamixer -i 5 ;;
	5) pamixer -d 5 ;;
	3) pgrep -x dunst >/dev/null && notify-send "<b>Volume module:</b>
- Shows volume 🔊, 🔇 if muted.
- Middle click to mute.
- Scroll to change."
esac

[ "$(pulsemixer --get-mute)" = "1" ] && printf "🔇\\n" && exit

vol=$(pamixer --get-volume | awk '{print $1}')

if [ "$vol" -gt "70" ]; then
	icon="🔊"
elif [ "$vol" -lt "30" ]; then
	icon="🔈"
else
	icon="🔉"
fi

printf "%s %s%%\\n" "$icon" "$vol"
